title: "$J01010111_"
subtitle: "infosec"
description: >- # this means to ignore newlines until "baseurl:"
  "$J01010111_'s blog."

url: "https://j01010111.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: "/home"
      url: /
    - text: "/whoami"
      url: /whoami
    - text: "/blog"
      url: /blog
#    - text: /buymeacoffee :)
#      url: /contact
#    - text: YouTube
#      url: {{https://youtube.com}}
# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: "$J01010111_"
author_bio: "Hi, my name is Jonathan. I built this site to practice my English skills and share content about infosec."
author_disclaimer: "All thoughts and opinions expressed here are my own, and may not be representative of my employer, or any other entity unless I am specifically quoting someone. This website and content included is provided “as is”, without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose, and noninfringement."
author_product_mentions: "There are many security tools, products, and services on the market today and I utilise many on a daily basis. Any mention of a particular tool, product, or service is on my own accord and is no way sponsored unless otherwise stated."
author_contact: ""
author_share: "Absolutely, provided you give attribution. Consider the work here licensed under the Creative Commons Attribution 4.0 International License."
#author_email: "john@doe"
author_location: Argentina
author_website_url: "https://j01010111.github.io"
typewrite-text: "welcome to my blog, here you can find posts about infosec and IT."
#hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img
hero_cover_img: back.jpg

# Experiences
author_work_experiences:
            - company_name:
              company_logo:
              company_url:
              designation:
              description:
              visibility: false
            - company_name:
              company_logo:
              company_url:
              designation:
              description:
              visibility: false

# Education
author_education_details:
              - college_logo:
                college_name:
                college_url:
                college_degree:
                description:
                visibility: false

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: false
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: false

# social links
twitter_username: "j01010111"
github_username:  "j01010111"
#facebook_username: johndoe
#linkedin_username: johndoe
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe
#youtube_username: johndoe
#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
#hyvor_talk_website_id: 476

# wakatime username (coding activity)
#wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
#formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: "J01010111"
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: false
show_author_education_details: false
show_author_project_details: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: false
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
 # - jekyll-admin

# Jekyll Admin Config
#jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
#  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - admin
destination: ./build
